### ISSUE TITLE
Make collection name customizable

### ISSUE THREAD

**Issue by qqilihq** [NodePit/node-migrate-state-store-mongodb#2]

**Comment by dantehemerson** [comment]
Can I take this issue?

I was thinking about add to constructor an object configuration param

So you can create the instance like this:

```js
new MongoStateStore({
   uri: 'mongodb://localhost:27017/myapp',
   collectionName: 'custom-collection', // By default we can use migrations
})
```
what do you think?

**Comment by qqilihq** [comment]
Hi there! 

MRs will be greatly appreciated :-) If you could make it backwards-compatible, so that we can still pass a simple string as currently, even better!

In case of any questions, feel free to get in touch.

**Comment by qqilihq** [comment]
Thanks again for this @dantehemerson! This is now on NPM as v2.1.0 🎉
