### ISSUE TITLE
npm install @types/migrate Error

### ISSUE THREAD

**Issue by ceciliazcx** [NodePit/node-migrate-state-store-mongodb#5]
Hi here,
I tried to use this library. but it keep asking me to install @types/migrate but this library does not exist. Could you help me with this? 
```
Try `npm install @types/migrate` if it exists or add a new declaration (.d.ts) file containing `declare module 'migrate';`

54 import * as migrate from 'migrate';
```

**Comment by qqilihq** [comment]
Hi,

this issue is not related to this library, but rather to your project setup.

You could adapt your TS config to be less strict (i.e. not require @types) or add a @ts-ignore annotation to the import.

**Comment by ceciliazcx** [comment]
@qqilihq I did exactly as you said. but got other error. 

`TypeError: Store is not a constructor
`
