### ISSUE TITLE
TypeError: Store is not a constructor

### ISSUE THREAD

**Issue by ceciliazcx** [NodePit/node-migrate-state-store-mongodb#6]
I wrote code with typescript. migrate create and migrate up/down with default state local save work fine.
When I tried to custom state file. I got the error as following:

```
var store = new Store(program.stateFile)
^
TypeError: Store is not a constructor
at Object. (\node_modules\migrate\bin\migrate-up:64:13)
```

Could anyone help with this?

**Comment by qqilihq** [comment]
Not related to `node-migrate-state-store-mongodb`.
