### ISSUE TITLE
Run from CLI

### ISSUE THREAD

**Issue by retani** [NodePit/node-migrate-state-store-mongodb#9]
How can I run this from CLI  – and how would I set the MONGO URL?

**Comment by qqilihq** [comment]
Write a wrapper script as seen in the readme. Call this from CLI.

**Comment by retani** [comment]
Thanks for the quick reply and the contributing this package. 

Here is an example wrapper for using the `migrate` cli command with state storage in your mongo db:

```
// migrate.js

var migrate = require('migrate')
const { MongoStateStore } = require('@nodepit/migrate-state-store-mongodb');

const MONGODB_URI = "mongodb://localhost:27017"

module.exports = class MyMongoStateStore extends MongoStateStore {
  constructor() {
    super(MONGODB_URI)
  }
}
```

usage:
`migrate up --store=./migrate.js`
`migrate down --store=./migrate.js`

**Comment by qqilihq** [comment]
Many thanks for posting this here -- to be honest, we do not use the “pure” CLI of `migrate` at all, but invoke it through the API, so this hadn’t even occurred to me. Good to see this alternative! :-)

I’ll update the readme with your example!

**Comment by qqilihq** [comment]
TODO: Update readme.md

**Comment by retani** [comment]
> we do not use the “pure” CLI of `migrate` at all, but invoke it through the API

This info is somehow missing from https://github.com/tj/node-migrate as well. 

I finally added `"migrate:up": "migrate up --store=./migrate.js"` to scripts in package.json, so in the command that I actually run in CLI is `npm run migrate:up`. It's almost like migrations in Ruby on Rails.
